site_name: ComfyUI Wiki
site_url: https://samsonxxxx.github.io/comfy-wiki/

theme:
  name: material
  language: ru
  base_url: /comfy-wiki/

nav:
  - Главная: index.md
  - Установка и интерфейс: install.md
  - Workflow:
      - SDXL портрет: workflow-sdxl.md
      - Видео: workflow-video.md
  - Ноды и расширения:
      - FLUX: flux.md
      - IPAdapter: ipadapter.md
  - Полезные ссылки: links.md
  - FAQ: faq.md
