site_name: ComfyUI Wiki
theme:
  name: material
  language: ru

nav:
  - Главная: index.md
  - Установка и интерфейс:
      - Быстрый старт: quickstart.md
  - Интерфейс:
      - Горячие клавиши и лайфхаки: hotkeys.md
  - Workflows:
      - SDXL:
          - SDXL Txt2Img: sdxl-txt2img.md
          - SDXL Img2Img: sdxl-img2img.md
      - FLUX:
          - FLUX Txt2Img: flux-txt2img.md
          - FLUX Img2Img: flux-img2img.md
      - Inpainting:
          - SDXL inpaint: sdxl-inpaint.md
          - FLUX inpaint: flux-inpaint.md
      - IPadapters, Control net, Reactor и прочие инструменты:
          - SDXL IPadapter + Instant ID: sdxl-ipadapter.md
          - SDXL Control net: sdxl-controlnet.md
      - Upscales/hires/hand fix, face detailer и прочие улучшения:
          - SDXL upscales: sdxl-upscales.md
          - 1: SDXL_handfix_upscale_ART.md
          - FLUX upscales: flux-upscales.md
      - Видео и анимация: video.md
  - Работа с LoRA:
      - Интересные лоры:
          - SDXL лоры: sdxl-lora.md
          - SDXL лоры на стиль: sdxl-lora-style.md
          - SDXL лоры персонажей: sdxl-lora-characters.md
          - FLUX лоры: flux-lora.md
          - FLUX лоры на стиль: flux-lora-style.md
          - FLUX лоры персонажей: flux-lora-characters.md
  - Советы и отладка:
      - Распространённые ошибки: tips-errors.md
      - Оптимизация производительности: tips-performance.md
  - Галерея примеров:
      - Примеры схем: gallery-schemes.md
      - Результаты до/после: gallery-before-after.md
  - Полезные ссылки: links.md
  - FAQ: faq.md
