backend:
  name: github
  repo: samsonxxxx/comfy-wiki
  branch: main
  squash_merges: true

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Страницы"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Текст", name: "body", widget: "markdown"}
      - {label: "Изображения", name: "images", widget: "list", allow_add: true, field:
          {label: "Изображение", name: "image", widget: "image"}}
